import './globals.css'

export const metadata = {
  title: 'User Management',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="container-fluid" style={{ padding: '0px 0 0px 0' }}>
          {children}
        </div>
      </body>
    </html>
  )
}